### PR TITLE
README: Application upload commands

### PR DESCRIPTION
**Pull request by DrZlo13**
You can use `scripts/storage.py` to upload files to flipper.

### CODE REVIEW

**Comment by dcoles** [comment]
Hi @DrZlo13,

Thanks for the update to the README! I made the mistake of setting everything up in WSL before realizing that I wouldn't be able to use the COM port. It gets pretty tiring copying it by hand every time.

**Comment by DrZlo13** [comment]
@dcoles you can definitely use usb-cdc in WSL thru [usbipd on WSL2](https://github.com/dorssel/usbipd-win/wiki/WSL-support) or natively on WSL1.

Also, can i ask, why do you use WSL? Just for rustup?

**Comment by DrZlo13** [comment]
> I'm not sure if [flipperzero-firmware](https://github.com/flipperdevices/flipperzero-firmware) has support for Windows builds yet.

Our toolchain/build tool natively supports x86\64 Windows, Linux and MacOS (and works through Rosetta on M1). All you need is to clone FW repository via git and call fbt.

We also noticed that we can make life easier for developers writing in other languages by adding `prebuild_command` to the application's manifest. In your case it would look like:
application.fam:
```App(
     ...
     prebuild_command="cd applications_user/hello_rust && cargo build --release",
     ...
)```

**Comment by DrZlo13** [comment]
Are you sure that this is the correct implementation of R_ARM_THM_MOVW_ABS_NC and R_ARM_THM_MOVT_ABS relocations?
image

```
 *((uint32_t*)relAddr) += symAddr;
```

**Comment by dcoles** [comment]
@DrZlo13 OK, so it turned out to be little more complex than "just a mask", but the good news is that it fixed all the crashes that were happening when calling into the standard library.

https://github.com/dcoles/flipperzero-firmware/commit/064125ca6ca1203fe72da3a7f18c7e110ae27953

**Pull request merged**
